#!/bin/bash

####################################
#Used to extract files from redmine#
####################################

#request for assembly name
echo "Enter assembly  name"
read dir

#request redmine ticket number
echo "Enter Redmine ticket number"
read num

mkdir /hive/users/chrisv/tracks/$dir 
cat  /hive/data/genomes/$dir/redmine$num/redmine.$dir.file.list > /hive/users/chrisv/tracks/$dir/FileList.txt 
